import RegistrationPeriod from '../utils/types/RegistrationPeriod'
import Specialization from '../utils/types/Specialization'
import { Educator } from '../utils/types/User'

const periods: RegistrationPeriod[] = [
  {
    id: '1',
    name: 'Period 1',
    startDate: new Date('2020-01-01'),
    endDate: new Date('2020-01-31'),
    topics: [
      {
        id: '4',
        name: 'Topic 4',
        description: 'Description 4',
        specialization: Specialization.INFORMATION_TECHNOLOGY,
        outcomes: ['Outcome 1', 'Outcome 2', 'Outcome 3'],
        numberOfMembers: 2,
        members: ['5'],
        educatorId: '2',
        evaluationMembers: [],
      },
      {
        id: '5',
        name: 'Topic 5',
        description: 'Description 5',
        specialization: Specialization.COMPUTER_NETWORKING,
        outcomes: ['Outcome 1', 'Outcome 2', 'Outcome 3'],
        numberOfMembers: 2,
        members: ['6'],
        educatorId: '3',
        evaluationMembers: [],
      },
      {
        id: '7',
        name: 'Topic 7',
        description: 'Description 7',
        specialization: Specialization.COMPUTER_NETWORKING,
        outcomes: ['Outcome 1', 'Outcome 2', 'Outcome 3'],
        numberOfMembers: 2,
        members: ['7'],
        educatorId: '3',
        evaluationMembers: [],
      },
      {
        id: '9',
        name: 'Topic 9',
        description: 'Description 4',
        specialization: Specialization.ARTIFICIAL_INTELLIGENCE,
        outcomes: ['Outcome 1', 'Outcome 2', 'Outcome 3'],
        numberOfMembers: 2,
        members: ['8'],
        educatorId: '2',
        evaluationMembers: [],
      },
      {
        id: '10',
        name: 'Topic 10',
        description: 'Description 5',
        specialization: Specialization.ARTIFICIAL_INTELLIGENCE,
        outcomes: ['Outcome 1', 'Outcome 2', 'Outcome 3'],
        numberOfMembers: 2,
        members: ['9', '8'],
        educatorId: '3',
        evaluationMembers: [],
      },
      {
        id: '11',
        name: 'Topic 11',
        description: 'Description 7',
        specialization: Specialization.COMPUTER_NETWORKING,
        outcomes: ['Outcome 1', 'Outcome 2', 'Outcome 3'],
        numberOfMembers: 2,
        members: ['7'],
        educatorId: '3',
        evaluationMembers: [],
      },
    ],
  },
  {
    id: '2',
    name: 'Period 2',
    startDate: new Date('2020-02-01'),
    endDate: new Date('2020-02-29'),
    topics: [
      {
        id: '1',
        name: 'Topic 1',
        description: 'Description 1',
        specialization: Specialization.SOFTWARE_ENGINEER,
        outcomes: ['Outcome 1', 'Outcome 2', 'Outcome 3'],
        numberOfMembers: 2,
        educatorId: '3',
        members: ['5'],
        evaluationMembers: [],
      },
      {
        id: '2',
        name: 'Topic 2',
        description: 'Description 2',
        specialization: Specialization.SOFTWARE_ENGINEER,
        outcomes: ['Outcome 1', 'Outcome 2', 'Outcome 3'],
        numberOfMembers: 2,
        educatorId: '4',
        members: ['6'],
        evaluationMembers: [],
      },
      {
        id: '3',
        name: 'Topic 3',
        description: 'Description 3',
        specialization: Specialization.INFORMATION_TECHNOLOGY,
        outcomes: ['Outcome 1', 'Outcome 2', 'Outcome 3'],
        numberOfMembers: 2,
        educatorId: '3',
        members: ['7'],
        evaluationMembers: [],
      },
      {
        id: '6',
        name: 'Topic 6',
        description: 'Description 6',
        specialization: Specialization.COMPUTER_NETWORKING,
        outcomes: ['Outcome 1', 'Outcome 2', 'Outcome 3'],
        numberOfMembers: 2,
        educatorId: '4',
        members: ['9'],
        evaluationMembers: [],
      },
    ],
  },
]

export default periods
